### ISSUE TITLE
Failed to dlopen libcuda.so in WSL environment

### ISSUE THREAD

**Issue by kkraus14** [NVIDIA/cuda-python#17]
```
from cuda import cuda
cuda.cuInit(0)
```
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [2], in <module>
----> 1 cuda.cuInit(0)

File ~/miniconda3/envs/dev/lib/python3.8/site-packages/cuda/cuda.pyx:8876, in cuda.cuda.cuInit()

File ~/miniconda3/envs/dev/lib/python3.8/site-packages/cuda/ccuda.pyx:17, in cuda.ccuda.cuInit()

File ~/miniconda3/envs/dev/lib/python3.8/site-packages/cuda/_cuda/ccuda.pyx:3553, in cuda._cuda.ccuda._cuInit()

File ~/miniconda3/envs/dev/lib/python3.8/site-packages/cuda/_cuda/ccuda.pyx:424, in cuda._cuda.ccuda.cuPythonInit()

RuntimeError: Failed to dlopen libcuda.so
```

This is because in a WSL environment `libcuda.so` lives in `/usr/lib/wsl/lib` which is not in the default search path of dlopen. For libraries that link against `libcuda` this isn't a problem because there's a file at `/etc/ld.so.conf.d/ld.wsl.conf` which instructs the linker as to where it can find the libraries, but unfortunately dlopen doesn't use this.

As a workaround, adding `/usr/lib/wsl/lib` to the `LD_LIBRARY_PATH` environment variable resolves the problem.

**Comment by kkraus14** [comment]
Also, in the `ldconfig` cache it looks like others load `libcuda.so.1` so only that entry is cached which would be another path for dlopen to find the needed library:
```
...
        libcudart.so (libc6,x86-64) => /usr/local/cuda-11.5/targets/x86_64-linux/lib/libcudart.so
        libcuda.so.1 (libc6,x86-64) => /usr/lib/wsl/lib/libcuda.so.1
        libcublasLt.so.11 (libc6,x86-64) => /usr/local/cuda-11.4/targets/x86_64-linux/lib/libcublasLt.so.11
...
```

**Comment by jakirkham** [comment]
Maybe similar to issue ( https://github.com/rapidsai/cudf/issues/10308 )?

**Comment by vzhurba01** [comment]
I've merged commit [15935e5](https://github.com/NVIDIA/cuda-python/commit/15935e5f464951a89836b0eeda36b3b72ed7ed57) that should resolve this.

@kkraus14 do you still get this error?
As of right now this fix is only on the repo and it still needs to be propagated to PyPI/Conda.

**Comment by kkraus14** [comment]
> I've merged commit [15935e5](https://github.com/NVIDIA/cuda-python/commit/15935e5f464951a89836b0eeda36b3b72ed7ed57) that should resolve this.
> 
> @kkraus14 do you still get this error? As of right now this fix is only on the repo and it still needs to be propagated to PyPI/Conda.

Just built the latest main branch and confirmed that it fixed the problem and passed the pytests. Closing, thanks @vzhurba01!
